test:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: butterfly
  username: butterfly
  password: butterfly
  host: localhost
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: butterfly
  username: butterfly
  password: butterfly
  host: localhost
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  # socket:   <%=ENV['OPENSHIFT_POSTGRESQL_DB_SOCKET']%>
  host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
